/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.stomas.rodolfo_gallardo_eva2.gui;

import com.stomas.rodolfo_gallardo_eva2.gui.exceptions.ArtistaException;
import com.stomas.rodolfo_gallardo_eva2.logica.Artista;
import com.stomas.rodolfo_gallardo_eva2.logica.Genero;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        llenarComboBox();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel_datos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_cant_canc = new javax.swing.JTextField();
        txt_cant_repro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmb_genero = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lb_resultado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_calculos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_datos.setBorder(javax.swing.BorderFactory.createTitledBorder("Artista"));
        panel_datos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Genero:");
        panel_datos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 110, -1));
        panel_datos.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 110, -1));

        jLabel2.setText("Cantidad de canciones subidas:");
        panel_datos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 180, -1));
        panel_datos.add(txt_cant_canc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 90, -1));

        txt_cant_repro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cant_reproActionPerformed(evt);
            }
        });
        panel_datos.add(txt_cant_repro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 90, -1));

        jLabel4.setText("Cantidad de reproducciones:");
        panel_datos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 180, -1));

        panel_datos.add(cmb_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jLabel3.setText("Nombre:");
        panel_datos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 110, -1));

        getContentPane().add(panel_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, 240));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pago Spotify"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jLabel5.setText("USD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        lb_resultado.setText("---");
        jPanel1.add(lb_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 100, -1));

        jLabel6.setText("Resultado:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 600, 120));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(list_calculos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, 580, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 600, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cant_reproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cant_reproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cant_reproActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Artista a = new Artista();
            a.setNombre(txt_nombre.getText());
            a.setCant_canciones_subidas(Integer.parseInt(txt_cant_canc.getText()));
            a.setCant_reproducciones(Integer.parseInt(txt_cant_repro.getText()));
            
            // Obtener el género seleccionado del combo box
            Genero generoSeleccionado = (Genero) cmb_genero.getSelectedItem();
            // Si el género es válido, asignarlo al artista
            a.setEnum_genero(generoSeleccionado);
            
            lb_resultado.setText(a.calcularPago() + "");
            
            lista_artistas.add(a);
            cargarLista();
        } catch (ArtistaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    private void llenarComboBox() {
        cmb_genero.setModel(new DefaultComboBoxModel<>(Genero.values()));
    }

    ArrayList<Artista> lista_artistas = new ArrayList<>();

    public void cargarLista() {
        DefaultListModel<Artista> model = new DefaultListModel<>(); // Modelo para el JList
        // Iterar sobre la lista
        for (Artista item : lista_artistas) { //Por cada elemento item representa un elemento de lista_personas
            model.addElement(item); // Agregar cada persona al modelo
        }
        list_calculos.setModel(model);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Genero> cmb_genero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_resultado;
    private javax.swing.JList<Artista> list_calculos;
    private javax.swing.JPanel panel_datos;
    private javax.swing.JTextField txt_cant_canc;
    private javax.swing.JTextField txt_cant_repro;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
